### ISSUE TITLE
Readme.md tips

### ISSUE THREAD

**Issue by Wiebsonice** [joanpadolina/frontend-applications#1]
* Probeer een korte inleiding te schrijven over het project
* De afbeelding van je pagina is in mijn ogen iets te groot, en doordat ie leeg is niet heel relevant.
* Misschien is het handig als je uitlegd met stappen in een lijst hoe je je project moet instaleren?
* Misschien iets over de API uitleggen? 
* Je kan nog een License toevoegen
* Linkje toevoegen naar je wiki kan handig zijn.

**Comment by joanpadolina** [comment]
thanks voor de feedback die ik nooit heb afgesloten! wel verwerkt haha
